apiVersion: v1
kind: Service
metadata:
  name: mayte-app-service
  labels:
    app: mayte-app
spec:
  type: NodePort
  
  selector:
    app: mayte-app
  
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080