apiVersion: v1
kind: Service
metadata:
  name: cicd-kubernetes-mayte-service
  labels:
    app: cicd-kubernetes-mayte
spec:
  type: LoadBalancer
  selector:
    app: cicd-kubernetes-mayte
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080